//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace battleship.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 54")]
        public global::System.Drawing.Point puntoInicial5 {
            get {
                return ((global::System.Drawing.Point)(this["puntoInicial5"]));
            }
            set {
                this["puntoInicial5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 90")]
        public global::System.Drawing.Point puntoInicial4 {
            get {
                return ((global::System.Drawing.Point)(this["puntoInicial4"]));
            }
            set {
                this["puntoInicial4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 126")]
        public global::System.Drawing.Point puntoInicial3 {
            get {
                return ((global::System.Drawing.Point)(this["puntoInicial3"]));
            }
            set {
                this["puntoInicial3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 162")]
        public global::System.Drawing.Point puntoInicial2a {
            get {
                return ((global::System.Drawing.Point)(this["puntoInicial2a"]));
            }
            set {
                this["puntoInicial2a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("103, 162")]
        public global::System.Drawing.Point puntoInicial2b {
            get {
                return ((global::System.Drawing.Point)(this["puntoInicial2b"]));
            }
            set {
                this["puntoInicial2b"] = value;
            }
        }
    }
}
